join_and_clean:
  min_abstract_length: 100
  database_whitelist: ["astronomy"]
keyword_extraction:
  no_below: 144  # multiplied 100 by (36/25), the ratio of years in this experiment compared to the last one
  no_above: 0.25
paper_organizer:
  no_below: 432  # multiplied 300 by (36/25), the ratio of years in this experiment compared to the last one
  no_above: 0.2
  min_mean_score: 0.015
  journal_blacklist: ["arXiv"]
  keyword_blacklist: "config/drop_features_08_03_2020.txt"
  use_keyword_count: False
topic_model:
        #topic_range: [100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650, 700, 750]
  topic_range: [25, 50, 75]
  lda_params:
    alpha: "auto"
    eta: "auto"
    iterations: 1000
    passes: 10
    chunksize: 1000000
    eval_every: 20
time_series:
  year_min: 2006
  year_max: 2019
  count_strategy: "weight+threshold"
  threshold: 0.05
