join_and_clean:
  limit: 500 # Use this for testing. Only takes this many papers from each year.
  min_abstract_length: 100
  database_whitelist: ["astronomy"]
keyword_extraction:
  no_below: 50
  no_above: 0.5
  spacy_model_name: "en_core_sci_sm"
paper_organizer:
  no_below: 100
  no_above: 0.25
  min_mean_score: 0.015
  journal_blacklist: ["arXiv"]
  keyword_blacklist: "config/drop_features.txt"
topic_model:
  topic_range: [20, 30, 50]
  lda_params: # More info: https://radimrehurek.com/gensim/models/ldamodel.html
    alpha: "auto"
    eta: "auto"
    iterations: 200
    passes: 10
    chunksize: 5000
    eval_every: 1
time_series:
  year_min: 1997
  year_max: 2010
